spring.datasource.url=jdbc:mysql://localhost:3306/student_placement?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false

server.port=8080

# Brevo SMTP Configuration (Sends to Real Inboxes)
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=a7491e001@smtp-brevo.com
spring.mail.password=xsmtpsib-2a90f64f41d2982ba2bce824d0b2b166338b031215c7a79495f3b7121d96b39d-lAtgM2Re4IlkHwU5
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=false
